version: '3.5'
services:
  app:
    image: $APP_IMAGE
    container_name: $APP_CONTAINER
    depends_on:
      - db
    env_file:
      - .env
    ports:
      - $APP_PORT:$APP_PORT
    expose:
      - $APP_PORT
    volumes:
      - $APP_VOLUME
  db:
    image: $DB_IMAGE
    container_name: $DB_CONTAINER
    env_file:
      - .env
    expose:
      - $DB_PORT
networks:
  default:
    name: $NETWORK
